app/connectors/ExchangeObjects.scala
app/controllers/ApplicationController.scala
app/repositories/application/TestDataRepository.scala
app/services/testdata/CreatedStatusGenerator.scala
it/repositories/ApplicationRepositorySpec.scala
it/repositories/DiagnosticReportRepositorySpec.scala
it/repositories/application/GeneralApplicationMongoRepositorySpec.scala
test/controllers/ApplicationControllerSpec.scala
test/controllers/DiagnosticReportControllerSpec.scala
test/controllers/ReportControllerSpec.scala

- Fix a typo of 'ajustments' for the new project, no more misspelt audit logs - hurray!
- Update the default framework name in faststream to match faststream-frontend (this was also stopping the test data generator users being properly loaded when testing
Tangentially related to work on FSET-647 (we can now use the generator which will save us lots of time)

Update static 'framework name' in project to FastStream-2016 (fixes Test Data Generator users)

---

app/connectors/AuthProviderClient.scala

Relies on internal PR - auth-provider/pull/43

Update faststream to use the updated auth provider remove-all call

---

app/model/ApplicationValidator.scala

the method hasGis is intented to check if you have a value in hasGis, not to check if that value is true.

Bug fix in Application Validator when gis = false

---

test/services/onlinetesting/OnlineTestServiceSpec.scala

When using Future.successful and returning Unit, Unit should be explicitly given

Fix warnings from the Future

---

app/scheduler/onlinetesting/EvaluatePhase1ResultJob.scala

The previous implementation was printing each character of the string on a new line

Fix logging of batch failures

---

app/repositories/onlinetesting/Phase1TestRepository.scala
app/services/onlinetesting/Phase1TestService.scala
it/repositories/onlinetesting/Phase1TestRepositorySpec.scala
test/services/onlinetesting/Phase1TestServiceSpec.scala

Check the resultsReadyToDownload flag and whether we already have tests saved or not when selecting candidates for the results scheduler.
If we have all the results for active tests then set the progress status to PHASE1_TESTS_RESULTS_RECEIVED.

Change mongo query for results ready scheduler.

---

app/model/events/AuditEvents.scala
app/model/events/DataStoreEvents.scala
app/services/onlinetesting/Phase3TestCallbackService.scala
app/services/onlinetesting/Phase3TestService.scala
test/controllers/LaunchpadTestsControllerSpec.scala
test/services/onlinetesting/Phase3TestServiceSpec.scala

Good spot @satishkamatam - would you care to review?

Mark application as results received when any results callbacks from launchpad are received

---

app/services/events/EventService.scala
app/services/onlinetesting/Phase3TestService.scala

Fixed some orphaned futures and a minor tidy up to the event sink interface to make it easier to use with blocks that do not use futures

Launchpad fix orphaned futures

---

app/controllers/OnlineTestController.scala
app/model/Exceptions.scala
app/services/onlinetesting/Phase2TestService.scala
test/controllers/OnlineTestsControllerSpec.scala
test/services/onlinetesting/Phase2TestServiceSpec.scala

Added logic to take care of an expired phase 2 test for invigilated e-tray.
In this case a 403 will be returned back to the client, rather than the 404 for failed verification.

fset-814 added expired test scenario

---

app/model/command/testdata/GeneratorConfig.scala
app/services/onlinetesting/Phase2TestService.scala

This PR is to fix a couple of minor issues:
1) there was a bug preventing us from setting start/expiry date for phase2 test via test generator
2) Regarding the invigilated e-tray token verification, the check for expired test is now done if, and only if, the access code is valid. This to avoid brute force attack meant to grab a valid user email.

FSET-814: bug fixing

---

app/connectors/paritygateway/ParityGatewayClient.scala
app/model/events/AuditEvents.scala
app/model/events/DataStoreEvents.scala
app/scheduler/parity/ParityExportJob.scala
app/services/parity/ParityExportService.scala
app/services/testdata/faker/DataFaker.scala
it/repositories/CommonRepository.scala
it/repositories/MediaRepositorySpec.scala
it/repositories/parity/ParityExportMongoRepositorySpec.scala
test/scheduler/parity/ParityExportJobSpec.scala

- Add tests for parity export
- Make sure empty media strings are None during export. 
- Fix bug with 'prefer not to say' in test data generation
- Audit exported applications
TODO: Tests for ParityExportService

FSET-1011: Parity Export: Add tests, audit, tweaks from live testing

---

app/repositories/application/GeneralApplicationRepository.scala
app/scheduler/allocation/ConfirmAttendanceReminderJob.scala
app/scheduler/onlinetesting/SendInvitationJob.scala
app/services/onlinetesting/OnlineTestFailureService.scala
app/services/reporting/AnswerProcessor.scala
it/repositories/ApplicationRepositorySpec.scala
project/MicroService.scala

Adding the warn-value-discard should help with issues where futures are orphaned accidentally with map instead of flatMap, and other similar circumstance

Add -Ywarn-value-discard scalac option for main compile and fix issues

---

app/repositories/onlinetesting/OnlineTestEvaluationRepository.scala
app/repositories/onlinetesting/OnlineTestRepository.scala
it/repositories/CommonRepository.scala
it/repositories/Phase1TestEvaluationSpec.scala
it/repositories/Phase2TestEvaluationSpec.scala
it/repositories/Phase3TestEvaluationSpec.scala
it/repositories/onlinetesting/Phase1EvaluationMongoRepositorySpec.scala
it/repositories/onlinetesting/Phase1TestRepositorySpec.scala
it/repositories/onlinetesting/Phase2EvaluationMongoRepositorySpec.scala
it/repositories/onlinetesting/Phase2TestRepositorySpec.scala
it/repositories/onlinetesting/Phase3EvaluationMongoRepositorySpec.scala
it/testkit/MongoRepositorySpec.scala

The previous scheme of not recording callbacks for tests which have expired caused issues when the tests were extended. The following changes have been made in this PR
-  I have moved the code to the query that selects candidates for the rules evaluation. This means that the test scores will be successfully downloaded for Cubiks tests, ensuring the Cubiks test was successfully completed and recorded. It should make it easier to answer support queries for candidates who believe they did the test before expiry. 
- The phase3/video rules evaluator didn't take into account expiry either, but now should
- The tests were fairly slow as they are doing the setup in series. I have improved the low hanging fruit

FSET-1008 Move test expiry to test score evaluation

---

app/scheduler/parity/ParityExportJob.scala
app/services/parity/ParityExportService.scala

Found during testing, fset-faststream doesn't throw any errors if an export fails

Ensure errors with parity exports are reported, remove debug logging

---

app/connectors/testdata/ExchangeObjects.scala
app/controllers/testdata/TestDataGeneratorController.scala
app/model/ReminderNotice.scala
app/model/command/testdata/GeneratorConfig.scala
app/model/exchange/testdata/CreateCandidateInStatusRequest.scala
app/services/onlinetesting/phase3/Phase3TestService.scala
app/services/testdata/onlinetests/phase1/Phase1TestsInvitedStatusGenerator.scala
app/services/testdata/onlinetests/phase1/Phase1TestsResultsReceivedStatusGenerator.scala
app/services/testdata/onlinetests/phase2/Phase2TestsInvitedStatusGenerator.scala
app/services/testdata/onlinetests/phase3/Phase3TestsInvitedStatusGenerator.scala

Belongs with: https://github.tools.tax.service.gov.uk/HMRC/fset-faststream-admin-frontend/pull/158

FSET 1533: Allow bq and sjq setting in phase1testdata

---

app/config/microserviceAppConfig.scala
app/config/microserviceGlobal.scala
app/connectors/CubiksGatewayClient.scala
app/controllers/testdata/TestDataGeneratorController.scala
app/model/Commands.scala
app/model/PersistedObjects.scala
app/model/persisted/QuestionnaireAnswer.scala
app/model/persisted/QuestionnaireQuestion.scala
app/repositories/AssessmentCentreRepository.scala
app/repositories/NorthSouthIndicatorCSVRepository.scala
app/repositories/QuestionnaireRepository.scala
app/repositories/ReactiveRepositoryHelpers.scala
app/repositories/application/TestDataRepository.scala
app/repositories/onlinetesting/OnlineTestRepository.scala
app/repositories/package.scala
app/scheduler/onlinetesting/ProgressSdipForFaststreamCandidateJob.scala
app/services/AuditService.scala
app/services/applicationassessment/ApplicationAssessmentService.scala
app/services/onlinetesting/phase2/Phase2TestSelector.scala
app/services/reporting/SocioEconomicCalculator.scala
app/services/testdata/AllocationStatusGenerator.scala
app/services/testdata/AwaitingAllocationStatusGenerator.scala
app/services/testdata/CreatedStatusGenerator.scala
app/services/testdata/InProgressQuestionnaireStatusGenerator.scala
it/repositories/QuestionnaireRepositorySpec.scala
project/MicroService.scala
project/MicroServiceBuild.scala
test/connectors/CubiksGatewayClientSpec.scala
test/mocks/QuestionnaireInMemoryRepository.scala

- Added 'silencer' (@silent) to suppress warnings we can't do anything about (because of HMRC libraries or structural changes that we're not going to make just yet, mainly use of Play.application)
- Removed unused vars, default arguments and methods, added flags to the compiler to tell us about them as warnings in future
- Moved Question/Answer out of the PersistedObjects mega file (as it's deprecated and triggers a warning) to become QuestionnaireQuestion and QuestionnaireAnswer
I've run acceptance but of course encourage you to do the same kind reviewer :-)

Low-risk refactors to cut down on warnings

---

app/controllers/AssessmentScheduleController.scala
conf/app.routes
conf/application.conf
conf/assessment-centres-prod.yaml
conf/assessment-centres.yaml
it/repositories/AssessmentCentreYamlRepositorySpec.scala

- Resurrect the assessmentschedulecontroller but comment out lots of old methods. They will likely all be needed again soon, which is the reason i've not gone for a delete.
- Create a new endpoint to 'getAssessmentScheduleDatesByRegion'

FSET 1354: Display the availability schedule for assessors/qacs

---

app/services/testdata/TestDataGeneratorService.scala

In our QA environments this will add users with logins:
test_service_manager_1@mailinator.com (retained for legacy support, please try and use the new ones from now on)
test_techadmin@mailinator.com
test_service_admin@mailinator.com
test_assessor@mailinator.com
test_qac@mailinator.com

Generate a smattering of other roles when the database is cleared, to speed QA

---

app/controllers/testdata/TestDataGeneratorController.scala
app/services/testdata/TestDataGeneratorService.scala
conf/testOnlyDoNotUseInAppConf.routes

This is an initial stab at making the user generation dynamic. At the moment, I've used a flag for this `?generateDefaultAssessor=false`. I won't be surprised if we will want to add the same flag for the other types of roles. 
I can either make the others dynamic too via query params OR we provide a flag to turn them all on/off OR we just do for the one flag(assessors) and add for others as the need arises.
Thoughts?
_p.s I'm making this change because it is required for a test in FSET-1542_

FSET-1542: Provide flag for turning off test assessor generation

---

app/connectors/testdata/ExchangeObjects.scala
app/controllers/AssessmentScheduleController.scala
app/controllers/testdata/TestDataGeneratorController.scala
app/model/Commands.scala
app/repositories/ApplicationAssessmentRepository.scala
app/services/onlinetesting/phase3/Phase3TestEvaluation.scala
app/services/testdata/onlinetests/TestsPassedStatusGenerator.scala
app/services/testdata/onlinetests/phase1/Phase1TestsInvitedStatusGenerator.scala
app/services/testdata/onlinetests/phase2/Phase2TestsInvitedStatusGenerator.scala
app/services/testdata/onlinetests/phase3/Phase3TestsInvitedStatusGenerator.scala

not specified in generation request.
Tidy up some implicit formats.

Update TDG to save generate passmark evaluation for previous phases if

---

app/controllers/DayAggregateEventController.scala
app/repositories/events/EventsRepository.scala
conf/app.routes
it/repositories/event/EventsRepositorySpec.scala
test/controllers/DayAggregateEventsControllerSpec.scala
test/model/persisted/EventExamples.scala

Accept skill types in routes as a list from query params rather than a comma separated string path segment.

Refactor skill path parameters in ApplicationClient

---

app/repositories/assessmentcentre/AssessmentCentreRepository.scala
app/repositories/sift/ApplicationSiftRepository.scala
app/services/testdata/candidate/onlinetests/TestsPassedStatusGenerator.scala
it/repositories/CommonRepository.scala
it/repositories/assessmentcentre/AssessmentCentreRepositorySpec.scala
it/repositories/sift/ApplicationSiftRepositorySpec.scala

TDG and some repos were incorrectly using EvaluationResult.toPassmark to generate scheme evaluation results.

NoJira - Remove toPassmark calls from TDG

---

app/services/allocation/AssessorAllocationService.scala

When an assessor declines an event, they get removed from the event by the service admin. When this happens, they should not receive an email saying they were removed from an event.
Not sure if we want to merge this in yet. Final confirmation from Kev/Wamiq/Andy is required.
I believe Wamiq wanted me to ignore this because it might be too much work but the diff says otherwise 😉

Assessors who decline should not get removed email

---

app/repositories/sift/SiftAnswersRepository.scala
app/services/sift/ApplicationSiftService.scala
app/services/sift/SiftAnswersService.scala
it/factories/ITDateTimeFactoryMock.scala
it/repositories/ApplicationRepositorySpec.scala
it/repositories/application/FlagCandidateMongoRepositorySpec.scala
it/repositories/application/GeneralApplicationMongoRepositorySpec.scala
it/repositories/application/ReportingMongoRepositorySpec.scala
it/repositories/onlinetesting/ApplicationDataFixture.scala
it/repositories/onlinetesting/Phase1TestRepositorySpec.scala
it/repositories/schemepreferences/SchemePreferencesRepositorySpec.scala
test/services/sift/SiftAnswersServiceSpec.scala

When candidate submitting sift forms, only check if all the green siftable schemes have been submitted, rather than all siftable schemes.
When sifting a scheme, check against green schemes in currentSchemeStatus rather than
phase3 results to decide whether to update progress to SIFT_COMPLETE.

NoJira: Fix sift form submission and scheme sift when there are withdrawn schemes

---

app/services/sift/ApplicationSiftService.scala

and the candidate was not being marked as SIFT_COMPLETE.

NoJira: Fix case for SdipFaststream where Sdip is sifted before the FS schemes

---

app/repositories/CurrentSchemeStatusHelper.scala
app/services/assessmentcentre/AssessmentCentreService.scala
test/services/assessmentcentre/AssessmentCentreServiceSpec.scala

Please merge this first: https://github.com/hmrc/fset-faststream/pull/494
If candidate is in ASSESSMENT_CENTRE_SCORES_ACCEPTED:
And First residual preference = Green => Pass
Amber => No action
No first residual preference (all reds or withdrawn) => Fail

FSET-1711: Mark candidates as pass or fail after assessment centre evaluation

---

conf/schemes.yaml
test/repositories/CurrentSchemeStatusHelperSpec.scala
test/services/sift/ApplicationSiftServiceSpec.scala

This removes International as a scheme, updates DaT to Digital, Data & Technology, and gives GES_DS its proper name of Diplomatic Service (Economists). Also updated year for SDIP. This PR has corresponding frontend changes.

Updated scheme names (and remove International)

---

app/scheduler/NotifyAssessorsOfNewEventsJob.scala
conf/application.conf

@henricook The guards in for-comprehensions don't work as we expected so I have re-written the logic for this

Rewrite logic for sending daily summary emails to assessors

---

app/services/application/ApplicationService.scala

Keep PHASE2_TESTS_RESULTS_READY when rolling back candidates from phase1/phase2 failed notified

Minor rollback fix

---

app/config/microserviceAppConfig.scala
app/repositories/sift/ApplicationSiftRepository.scala
conf/application.conf

There are future tickets for QA which need sdipfaststream candidates to proceed past sift, thanks to the existing hotfix this is impossible, which is delaying QA. Make it configurable so we can turn it off in QA.

NOJIRA: Make sdipfaststream exclusion from sift configurable

---

app/model/Scheme.scala
app/services/sift/ApplicationSiftService.scala
app/services/sift/SiftAnswersService.scala
test/services/sift/SiftAnswersServiceSpec.scala

Sdip gets sifted later.
There was already code to deal with this *when another scheme got sifted by a sifter in the admin frontend* - but if Sdip is your *only* siftable scheme that's not going to happen. This handles that scenario, where your only siftable scheme is Sdip.

FSET-1820: Do not hold in sift if only sdip is siftable

---

app/repositories/SchemeRepository.scala
app/services/application/ApplicationService.scala
app/services/sift/ApplicationSiftService.scala
test/services/application/ApplicationServiceSpec.scala

Implemented the rules that determine when a candidate should be invited to FSAC after withdrawing from schemes

FSET-1780 advance to FSAC when withdrawing from schemes

---

app/services/testdata/TestDataGeneratorService.scala

Fix for test data generator qac user - set him to the correct role so we can now use him

Test data generator fix for QAC user

---

app/connectors/exchange/AssessorAllocationRequest.scala
app/controllers/AssessorController.scala
conf/app.routes

When there are a lot of assessors, the GET endpoint blows up as the request's
url becomes too long. This sends the request payload in the body of a
POST request

FSET-1837: Modify endpoint for multiple assessors' allocations from GET to POST

---

app/model/ProgressStatuses.scala
app/model/command/ProgressResponse.scala
app/model/report/ProgressStatusesReportLabels.scala
app/repositories/CommonBSONDocuments.scala
app/repositories/fsb/FsbRepository.scala
app/services/sift/ApplicationSiftService.scala
test/services/sift/ApplicationSiftServiceSpec.scala

added new state SIFT_FASTSTREAM_FAILED_SDIP_GREEN to identify sdip faststream candidates whose fast stream schemes have either been sifted out or have been withdrawn but whose sdip has been sifted in. These candidates should be invited to attend FSB

FSET-1866 Sdip FS candidates who have been sifted out of FS schemes or withdrawn should be invited to FSB if Sdip is sifted in

---

app/services/application/ApplicationService.scala
test/services/application/ApplicationServiceSpec.scala

Also consider candidates who should be progressed to ASSESSMENT_CENTRE_AWAITING_ALLOCATION but have not yet been picked up by the job and so are still in SIFT_COMPLETED when withdrawing from schemes, just leaving Sdip. These candidates should be progressed straight to FSB

FSET-1866 progress candidates straight to FSB who are in SIFT_COMPLETED and withdraw from all fs schemes, leaving just Sdip

---

app/services/sift/ApplicationSiftService.scala
test/services/sift/ApplicationSiftServiceSpec.scala

fix to move candidates who are still in the running for numeric schemes (which require a sift) and are no longer in the running for schemes requiring a form to be filled in after video interview into SIFT_READY status so they can be sifted

FSET-1871 progress candidates to SIFT_READY who are being put into SIFT_ENTERED by mistake

---

app/model/NotificationTestType.scala
app/scheduler/Scheduler.scala
app/scheduler/onlinetesting/SuccessTestJob.scala
conf/application.conf
it/repositories/application/GeneralApplicationMongoRepositorySpec.scala

Needs: https://github.com/hmrc/fset-email-renderer/pull/40

FSET-1878: Add a new scheduler for sdipfaststream phase 3 passes, and limit the old one to faststream only

---

.travis.yml
app/connectors/CubiksGatewayClient.scala
app/controllers/testdata/TestJobsController.scala
app/repositories/fileupload/FileUploadRepository.scala
conf/application.conf
conf/testOnlyDoNotUseInAppConf.routes
it/repositories/fileupload/FileUploadRepositorySpec.scala
it/testkit/MongoRepositorySpec.scala

Changed the CubiksGatewayClient to use the renamed cubiks gateway (fset-online-tests-gateway). Also added an endpoint to manually trigger the invitations to the online tests for each phase

FSET-1935 Use renamed cubiks gateway

---

app/controllers/CubiksTestsController.scala
app/model/persisted/sift/SiftTestGroupWithAppId.scala
app/repositories/sift/ApplicationSiftRepository.scala
app/services/NumericalTestsService.scala
test/controllers/CubiksTestControllerSpec.scala

* Handle main callback from cubiks via gateway
* Handle callback from candidate frontend(complete by token)

FSET-2043: Handle numerical test completion callbacks

---

app/config/microserviceAppConfig.scala
app/services/onlinetesting/phase2/Phase2TestSelector.scala
conf/application.conf
test/config/Phase2TestsConfigSpec.scala
test/services/onlinetesting/phase1/Phase1TestServiceSpec.scala
test/services/onlinetesting/phase2/Phase2TestSelectorSpec.scala
test/services/onlinetesting/phase2/Phase2TestServiceSpec.scala

Add ability to specify which eTray is selected instead of it being random. Used to test during campaign setup

FSET-2139 Add ability to specify which eTray is selected instead of it being random

---

app/connectors/OnlineTestsGatewayClient.scala
app/services/onlinetesting/phase2/Phase2TestService2.scala
test/services/onlinetesting/phase2/Phase2TestService2Spec.scala

Candidates were receiving 2 emails in phase 2(one per test). This ensures they receives just one email for both invitations.

FSET-2402: Ensure single email is sent for all P2 invitations

---

conf/schemes.yaml

To test if the schemes appear correctly for civil service eligibility.Setting the DAT to false from default True.

FSET-2535: DAT civilServantEligible is set false
