hmrc/fset-faststream

- app/common/FutureEx.scala
- app/repositories/application/GeneralApplicationRepository.scala
- app/repositories/application/TestDataRepository.scala
- app/services/onlinetesting/OnlineTestService.scala
- it/repositories/ApplicationRepositorySpec.scala
- test/controllers/ReportControllerSpec.scala
This PR contains minor refactors that don't warrant being split into individual PRs
> Minor refactors

- app/services/applicationassessment/ApplicationAssessmentService.scala
- app/services/onlinetesting/OnlineTestService.scala
- it/repositories/ApplicationRepositorySpec.scala
Most of this code has migrated to other PRs, so this is a very small bunch of cleanups
> Fixup some futures, method renaming and more explicit assertions

- app/services/testdata/Phase1TestsInvitedStatusGenerator.scala
- app/services/testdata/StatusGeneratorFactory.scala
based on guaranteed interview status.
> Update test data genny to create phase 1 sjq and bq or just bq tests

- app/repositories/application/OnlineTestRepository.scala
- it/repositories/OnlineTestRepositorySpec.scala
Fix the check for a fastpass candidate in nextCandidateReadyForOnlineTesting.  We should be using the
"fastPassReceived" flag.
> Fix the check for a fastpass candidate in nextCandidateReadyForOnlineTesting

- app/controllers/SchoolsController.scala
- app/model/School.scala
- app/repositories/SchoolsRepository.scala
- app/repositories/package.scala
- app/services/schools/SchoolsService.scala
- conf/app.routes
- test/services/schools/SchoolsServiceTest.scala
> FSET 782 - Added service to backend

- app/repositories/application/OnlineTestRepository.scala
- app/services/onlinetesting/OnlineTestService.scala
- app/services/testdata/Phase1TestsCompletedStatusGenerator.scala
- app/services/testdata/Phase1TestsStartedStatusGenerator.scala
Required for: https://github.tools.tax.service.gov.uk/HMRC/fset-faststream-admin-acceptance-tests/pull/14
> FSET 642 - Corrections and refactors from writing acceptance tests

- app/connectors/AuthProviderClient.scala
- app/connectors/ExchangeObjects.scala
- app/controllers/SearchForApplicantsController.scala
- app/repositories/application/GeneralApplicationRepository.scala
Dependent on: https://github.tools.tax.service.gov.uk/HMRC/csr-auth-provider/pull/3
> FSET-824: Update to auth provider requires POST instead of GET for find by first/last name

- app/repositories/application/GeneralApplicationRepository.scala
- app/repositories/package.scala
- it/repositories/ApplicationRepositorySpec.scala
This is a fix for the adjustment report as candidate with GIS and no adjustment for Venue or online testing SHOULD be included in the report (whereas they weren't)
> FSET-682: fixed issues spotted in QA

- app/config/microserviceAppConfig.scala
- app/repositories/onlinetesting/Phase1EvaluationRepository.scala
- app/scheduler/onlinetesting/EvaluatePhase1ResultJob.scala
- app/services/onlinetesting/EvaluatePhase1ResultService.scala
- conf/application.conf
- it/repositories/onlinetesting/Phase1EvaluationMongoRepositorySpec.scala
- test/scheduler/onlinetesting/EvaluatePhase1ResultJobSpec.scala
- test/services/onlinetesting/EvaluatePhase1ResultServiceSpec.scala
Reverts hmrc/fset-faststream#95
> Revert "Add batch size limit for phase1 evaluation"

- app/repositories/onlinetesting/Phase1TestRepository.scala
- app/repositories/onlinetesting/Phase2TestRepository.scala
> use the commonBSONDocuments helper methods to set the progress status

- app/services/onlinetesting/Phase1TestService.scala
- test/services/onlinetesting/Phase1TestServiceSpec.scala
Please first merge this PR: https://github.com/hmrc/fset-faststream/tree/batchLimitPhase1
> Remove results ready progress when application has been reset

- app/connectors/CubiksGatewayClient.scala
- app/repositories/onlinetesting/Phase2TestRepository.scala
accidentally overwriting the phase1 group.
> Fix cubiks endpoint in client.  Fix phase2 test insert - we were

- app/services/onlinetesting/Phase2TestService.scala
- test/services/onlinetesting/Phase2TestServiceSpec.scala
completed the manage adjsutments story FSET-656.
> Filter out adjustment candidates from the etray invite until we have

- app/repositories/QuestionnaireRepository.scala
https://jira.tools.tax.service.gov.uk/browse/FSET-698
This is a PR related to a bug discoved in fset-698
This is the only project involve in it
> Fset 698 Download the diversity report - ethnicity bug

- app/repositories/RandomSelection.scala
- test/repositories/RandomSelectionSpec.scala
- test/services/onlinetesting/EvaluatePhase1ResultServiceSpec.scala
Fix unit future return in evaluate phase 1 service spec.
> Tests for the batch size logic in RandomSelection

- app/services/testdata/InProgressSchemePreferencesStatusGenerator.scala
> Stop generating randim schemes in the test data genny for Edip

- app/repositories/CommonBSONDocuments.scala
- app/repositories/application/GeneralApplicationRepository.scala
- app/repositories/package.scala
- it/repositories/ApplicationRepositorySpec.scala
- Guard against multiple application submissions
- Ensure the application is in the right state to be submitted
> Fix multiple submission

- app/connectors/launchpadgateway/exchangeobjects/in/FinalCallbackRequest.scala
- app/connectors/launchpadgateway/exchangeobjects/in/FinishedCallbackRequest.scala
- app/connectors/launchpadgateway/exchangeobjects/in/QuestionCallbackRequest.scala
- app/connectors/launchpadgateway/exchangeobjects/in/SetupProcessCallbackRequest.scala
- app/connectors/launchpadgateway/exchangeobjects/in/ViewBrandedVideoCallbackRequest.scala
- app/connectors/launchpadgateway/exchangeobjects/in/ViewPracticeQuestionCallbackRequest.scala
- app/controllers/LaunchpadTestsController.scala
- app/model/persisted/phase3tests/LaunchpadTest.scala
- app/model/persisted/phase3tests/LaunchpadTestCallbacks.scala
- app/repositories/CivilServiceExperienceDetailsRepository.scala
- app/repositories/ContactDetailsRepository.scala
- app/repositories/application/GeneralApplicationRepository.scala
- app/repositories/assistancedetails/AssistanceDetailsRepository.scala
- app/repositories/contactdetails/ContactDetailsRepository.scala
- app/repositories/onlinetesting/OnlineTestRepository.scala
- app/repositories/onlinetesting/Phase3TestRepository.scala
- app/repositories/partnergraduateprogrammes/PartnerGraduateProgrammesRepository.scala
- app/repositories/schemepreferences/SchemePreferencesRepository.scala
- app/services/onlinetesting/Phase3TestCallbackService.scala
- app/services/onlinetesting/Phase3TestService.scala
- it/repositories/onlinetesting/Phase3TestRepositorySpec.scala
- test/controllers/LaunchpadTestsControllerSpec.scala
- test/services/onlinetesting/Phase3TestServiceSpec.scala
Requires: https://github.com/hmrc/fset-launchpad-gateway/pull/5
> FSET 869: Record all callbacks apart from reviewed (separate PR)

- app/repositories/BaseBSONReader.scala
- app/repositories/application/GeneralApplicationRepoBSONReader.scala
- app/repositories/application/GeneralApplicationRepository.scala
- app/repositories/application/ReportingRepoBSONReader.scala
- app/repositories/onlinetesting/OnlineTestEvaluationRepository.scala
- app/repositories/onlinetesting/OnlineTestRepository.scala
This is not part of a story in Jira.
As part as the ongoing refactor of General Application Repository, I have moved some code I missed in my last task to the corresponding BSONreader.
> Refactor general application

- conf/application.conf
53 was wrong, 46 is the right value.
> Interview id corrected for launchpad configuration

- app/services/testdata/InProgressPersonalDetailsStatusGenerator.scala
- app/services/testdata/faker/DataFaker.scala
- app/services/testdata/onlinetests/phase3/Phase3TestsResultsReceivedStatusGenerator.scala
- conf/application.conf
Changes to created phase3 callbacks in mongo for test data generator.
This is not part of any story but it will be useful in fset-724
> Test data generator phase3 tests results received

- app/model/Exceptions.scala
- app/services/testdata/StatusGeneratorFactory.scala
These PR should be done together:
https://github.com/hmrc/fset-faststream/pull/238
https://github.com/hmrc/fset-faststream/pull/242
and 58 PR in candidate-acceptance-test
and 45 PR in admin-acceptance-test
> Fset 896 test data generator improvement

- app/controllers/ReportingController.scala
- app/model/persisted/ApplicationForDiversityReport.scala
- app/model/persisted/ApplicationForOnlineTestPassMarkReport.scala
- app/model/report/ApplicationForOnlineTestPassMarkReportItem.scala
- app/model/report/CandidateProgressReportItem.scala
- app/model/report/DiversityReportItem.scala
- app/repositories/NorthSouthIndicatorCSVRepository.scala
- app/repositories/application/ReportingRepoBSONReader.scala
- app/repositories/application/ReportingRepository.scala
- it/repositories/NorthSouthIndicatorCSVRepositorySpec.scala
- it/repositories/application/ReportingMongoRepositorySpec.scala
- test/controllers/report/ReportingControllerSpec.scala
- test/mocks/application/ReportingInMemoryRepository.scala
- test/model/persisted/ApplicationForDiversityReportExamples.scala
- test/model/persisted/ApplicationForOnlineTestPassMarkReportExamples.scala
- test/model/report/ApplicationForDiversityReportItemExamples.scala
- test/model/report/CandidateProgressReportItemExamples.scala
- test/model/report/onlinetestpassmark/ApplicationForOnlineTestPassMarkReportItemExamples.scala
Need the corresponding admin frontend change to be merged afterwards: https://github.tools.tax.service.gov.uk/HMRC/fset-faststream-admin-frontend/pull/121
> Fset 959: SDIP diversity report

- app/repositories/onlinetesting/OnlineTestRepository.scala
- it/repositories/onlinetesting/Phase1TestRepositorySpec.scala
Ignore updates which do not match the application status predicate
> UpdateProgressStatus now ignores duplication 

- app/model/OnlineTestCommands.scala
- app/services/onlinetesting/Phase3TestService.scala
- test/services/onlinetesting/Phase3TestServiceSpec.scala
> FSET-963 Reschedule a new video interview when adjustments change

- app/controllers/fixdata/FixDataConsistencyController.scala
- app/model/command/FastPassPromotion.scala
- app/services/fastpass/FastPassService.scala
- conf/app.routes
- conf/application.conf
- test/services/fastpass/FastPassServiceSpec.scala
Add admin functionality to force candidate to fast pass accepted state
> Fset 1161: Mark Fast Pass candidates

- app/controllers/ReportingController.scala
- app/model/report/ApplicationForEdipReport.scala
- app/model/report/EdipReportItem.scala
- app/repositories/application/ReportingRepoBSONReader.scala
- app/repositories/application/ReportingRepository.scala
- conf/app.routes
- test/controllers/report/ReportingControllerSpec.scala
- test/mocks/application/ReportingInMemoryRepository.scala
> Added Edip report

- app/connectors/AuthProviderClient.scala
- app/connectors/CubiksGatewayClient.scala
- app/connectors/EmailClient.scala
- app/connectors/ExchangeObjects.scala
- app/model/Adjustments.scala
- app/model/OnlineTestCommands.scala
- conf/application.conf
- test/connectors/CubiksGatewayClientSpec.scala
> FSET-987 Migrate to HMRC email service and fset-email-renderer service.

- app/connectors/ExchangeObjects.scala
There are 6 PRs for this jira ticket:
-https://github.com/hmrc/fset-faststream/pull/338
-https://github.com/hmrc/fset-faststream-frontend/pull/197
-fset-faststream-admin-frontend
-fset-faststream-admin-acceptance-tests
-csr-auth-provider
-fset-email-renderer
> [Fset-1499] Manage existing admin user (edit/deactivate)

- app/config/microserviceAppConfig.scala
- app/connectors/AuthProviderClient.scala
- conf/application.conf
FSET-1501 and FSET-1499 bug 1 are related and should be merged together
4 PRs:
https://github.com/hmrc/fset-faststream/pull/340
https://github.com/hmrc/fset-faststream-frontend/pull/198
and front end admin faststream (2 PRs one for fset-1499-bug1 and the other for fset-1501
> [Fset-1501] End session for deactivating Admin users

- app/model/OnlineTestCommands.scala
Bug fix. Now you only need to have invigilated e-tray to be invited to -etray invigilated. Before you also needed to have requested online adjustments.
This is the only PR part of this ticket.
> [FSET-1550] Schedule the invigilated e-tray

- app/controllers/AssessorAvailabilityController.scala
- app/repositories/AssessorAvailabilityRepository.scala
- app/services/assessoravailability/AssessorAvailabilityService.scala
- conf/app.routes
- it/repositories/AssessorAvailabilityRepositorySpec.scala
- test/controllers/AssessorAvailabilityControllerSpec.scala
WIP until Ian's work gets merged
> FSET 1355: Add the top of the 'assessor availability summary page' - totals

- app/repositories/onlinetesting/OnlineTestEvaluationRepository.scala
- app/services/onlinetesting/ApplicationStatusCalculator.scala
- app/services/onlinetesting/OnlineTestResultsCalculator.scala
- app/services/onlinetesting/phase1/Phase1TestEvaluation.scala
Mostly added debug so it is obvious what is happening in the code
> FSET-1573 2018 edip

- app/model/ApplicationStatus.scala
- app/repositories/onlinetesting/OnlineTestEvaluationRepository.scala
- it/repositories/onlinetesting/Phase1EvaluationMongoRepositorySpec.scala
- it/repositories/onlinetesting/Phase2EvaluationMongoRepositorySpec.scala
- it/repositories/onlinetesting/Phase3EvaluationMongoRepositorySpec.scala
FSET-1627 Changes to support e-tray re-evaluation
> Fset 1627 Changes to support e-tray score re-evaluation

- app/services/testdata/candidate/RegisteredStatusGenerator.scala
> Use the skill type enum when creating the assessor users in the TDG so

- app/model/exchange/passmarksettings/PassMark.scala
- app/model/exchange/passmarksettings/PassMarkSettings.scala
- app/services/onlinetesting/phase1/Phase1TestEvaluation.scala
- app/services/onlinetesting/phase2/Phase2TestEvaluation.scala
- app/services/onlinetesting/phase3/Phase3TestEvaluation.scala
- test/controllers/Phase1PassMarkSettingsControllerSpec.scala
- test/model/exchange/passmarksettings/Phase1PassMarkSettingsSpec.scala
SchemeId fixes/migration - ready for review/merge
> SchemeId fixes/migration - ready for review/merge

- app/controllers/testdata/TestDataGeneratorController.scala
- app/services/testdata/admin/AssessorCreatedStatusGenerator.scala
The create assessor user endpoint in Test Data Generator could not create the availability which has been fixed in this PR.
> Fix assessor availability tdg endpoint

- app/config/microserviceAppConfig.scala
- app/controllers/testdata/TestDataGeneratorController.scala
- app/model/command/testdata/CreateEventRequest.scala
- app/model/persisted/eventschedules/Event.scala
- app/model/persisted/eventschedules/Session.scala
- app/model/testdata/CreateEventData.scala
- app/repositories/events/EventsConfigRepository.scala
- app/services/events/EventsParsingService.scala
- app/services/events/EventsService.scala
- app/services/testdata/faker/DataFaker.scala
- conf/application.conf
- conf/event-schedule.yaml
- test/controllers/EventsControllerSpec.scala
- test/model/persisted/EventExamples.scala
- test/services/events/EventsConfigRepositorySpec.scala
Moved the Events definition into Yaml and provided nested sessions (within the Events)
> Fset 1674 - Event/Sessions config spike

- app/model/command/testdata/CreateCandidateRequest.scala
- app/repositories/sifting/SiftingRepository.scala
- app/services/testdata/candidate/CandidateStatusGeneratorFactory.scala
- app/services/testdata/candidate/onlinetests/TestsPassedNotifiedStatusGenerator.scala
- it/repositories/sifting/SiftingRepositorySpec.scala
Sift candidates from PHASE3_TESTS_PASSED_NOTIFIED
> Fset 1633a PHASE3_TESTS_PASSED_NOTIFIED

- app/repositories/application/GeneralApplicationRepository.scala
This ensures that candidates in PHASE3_TESTS_PASSED_NOTIFIED are also eligible for allocation
> Candidates that have been notified are also eligible for allocation

- app/repositories/csv/FSACIndicatorCSVRepository.scala
- conf/FSAC_indicator_lookup_by_postcode.csv
- it/repositories/csv/FSACIndicatorCSVRepositorySpec.scala
**FSET-1678 Update look up by postcode file and default to Newcastle**
> FSET-1678 Update look up by postcode file and default to Newcastle

- conf/locations-and-venues.yaml
> Rename venues in config file

- app/repositories/sift/ApplicationSiftRepository.scala
- it/repositories/sift/ApplicationSiftRepositorySpec.scala
> NOJira: Fix query to populate scheme sift list when there are other withdrawn

- app/connectors/EmailClient.scala
- app/model/stc/EmailEvents.scala
- app/services/allocation/CandidateAllocationService.scala
- app/services/stc/handler/EmailEventHandler.scala
> FSET-1737. Send candidate FSB invitation

- app/connectors/EmailClient.scala
- app/controllers/testdata/TestJobsController.scala
- app/model/AssessorNewEventsJobInfo.scala
- app/model/Exceptions.scala
- app/model/persisted/eventschedules/Event.scala
- app/model/testdata/CreateEventData.scala
- app/repositories/AssessorRepository.scala
- app/repositories/AssessorsEventsSummaryJobsRepository.scala
- app/repositories/CollectionNames.scala
- app/repositories/events/EventsConfigRepository.scala
- app/repositories/events/EventsRepository.scala
- app/repositories/package.scala
- app/scheduler/NotifyAssessorsOfNewEventsJob.scala
- app/scheduler/Scheduler.scala
- app/services/AssessorsEventsSummaryJobsService.scala
- app/services/assessoravailability/AssessorService.scala
- app/services/events/EventsService.scala
- conf/application.conf
- conf/testOnlyDoNotUseInAppConf.routes
- it/repositories/AssessorRepositorySpec.scala
- it/repositories/AssessorsEventsSummaryJobsRepositorySpec.scala
- it/repositories/event/EventsRepositorySpec.scala
- test/controllers/CandidateAllocationControllerSpec.scala
- test/controllers/EventsControllerSpec.scala
- test/model/persisted/EventExamples.scala
- test/services/allocation/AssessorAllocationServiceSpec.scala
- test/services/allocation/CandidateAllocationServiceSpec.scala
- test/services/assessor/AssessorServiceSpec.scala
- test/services/events/EventsConfigRepositorySpec.scala
Email template: https://github.com/hmrc/fset-email-renderer/pull/26
> FSET-1713: Send notification to assessors when event is created manually

- app/model/stc/AuditEvents.scala
- app/repositories/SchemeRepository.scala
- app/repositories/application/GeneralApplicationRepository.scala
- app/services/application/ApplicationService.scala
- test/mocks/application/DocumentRootInMemoryRepository.scala
- test/services/application/ApplicationServiceSpec.scala
When withdrawing from schemes during sift, if there are only HR or Generalist left in the scheme list then progress the candidate to FSAC allocation.
> FSET-1744 Progress To FSAC after withdrawal

- app/controllers/EventsController.scala
- app/repositories/events/EventsRepository.scala
- app/services/events/EventsService.scala
- conf/app.routes
Frontend: https://github.tools.tax.service.gov.uk/HMRC/fset-faststream-admin-frontend/pull/271
> Add migration endpoint for events

- app/repositories/sift/ApplicationSiftRepository.scala
- app/services/sift/ApplicationSiftService.scala
- test/services/sift/ApplicationSiftServiceSpec.scala
BSON to ensure all sub-docs are correctly updated.
> NoJira: Multiple set statements do not work in mongo, so rework the sift update

- conf/event-schedule.yaml
Added FSB and Telephone interview events
> FSB and Telephone interview events

- app/services/sift/ApplicationSiftService.scala
> FSET-1644 Corrected sift progression to SIFT_COMPLETE - factor in sift fails along with passes

- app/repositories/SchemeRepository.scala
- app/services/application/ApplicationService.scala
- app/services/sift/ApplicationSiftService.scala
- app/services/sift/SiftAnswersService.scala
- conf/schemes.yaml
- test/services/application/ApplicationServiceSpec.scala
- test/services/sift/ApplicationSiftServiceSpec.scala
Some schemes do not require an evaluation(no pass/fail). If these schemes
are the green schemes after sift or form submission, the candidate should be
progressed to the right state.
> FSET-1731: Schemes without evaluation should be progressed to the right state

- app/controllers/DayAggregateEventController.scala
- app/model/exchange/Assessor.scala
- app/model/persisted/eventschedules/Event.scala
- app/repositories/AssessorRepository.scala
- conf/locations-and-venues.yaml
- test/controllers/DayAggregateEventsControllerSpec.scala
- test/model/persisted/EventExamples.scala
Artificially add a day aggregated event for the "Home" location for each day that has another event running.
> FSET-1791 Allow Assessors to add availability for wfh

- app/repositories/assessmentcentre/AssessmentCentreRepository.scala
- it/repositories/CommonRepository.scala
- it/repositories/assessmentcentre/AssessmentCentreRepositorySpec.scala
> Ensure that edip and sdip candidates are progressed to fsac when they

- app/repositories/application/GeneralApplicationRepository.scala
This should fix the admin acceptance tests
> Add fsac-indicator to allocated applications' projection

- app/model/persisted/eventschedules/VenueType.scala
- conf/event-schedule.yaml
- conf/locations-and-venues.yaml
Update event schedule from a CSV provided by CSHR
> NOJIRA: Update event schedule

- app/services/onlinetesting/phase1/EvaluatePhase1ResultService.scala
- app/services/onlinetesting/phase1/Phase1TestEvaluation.scala
- app/services/onlinetesting/phase2/EvaluatePhase2ResultService.scala
- app/services/onlinetesting/phase2/Phase2TestEvaluation.scala
- app/services/onlinetesting/phase3/EvaluatePhase3ResultService.scala
- app/services/onlinetesting/phase3/Phase3TestEvaluation.scala
- test/services/onlinetesting/phase1/EvaluatePhase1ResultServiceSpec.scala
- test/services/onlinetesting/phase1/Phase1TestEvaluationSpec.scala
Reverts hmrc/fset-faststream#547
> Revert "FSET-1800: Ensure Sdip is evaluated to Amber for SdipFastStream candidates"

- app/controllers/EventsController.scala
- app/repositories/events/EventsRepository.scala
- app/services/events/EventsService.scala
- conf/app.routes
- it/repositories/event/EventsRepositorySpec.scala
- test/controllers/EventsControllerSpec.scala
- test/model/persisted/EventExamples.scala
3 PRs:
https://github.com/hmrc/fset-faststream/pull/552
fset-faststream-admin-frontend
fset-faststream-admin-acceptance-tests
> [Fset-1787] Filter event schedule by FSB type

- app/services/fastpass/FastPassService.scala
- test/services/fastpass/FastPassServiceSpec.scala
The candidate dashboard does not show the right information when a FastPass candidate is auto-progressed to SIFT. This is because they do not have `currentSchemeStatus` and as a result, a lot of stuff will break. This PR sets the `currentSchemeStatus` for every scheme to `Green`.
**Reasoning:** If a candidate is auto-progressed to SIFT, we are essentially saying they have "passed" all online tests(P1, P2, P3). I have confirmed with Uchenna that this is fine but I think one final confirmation is required.
> FSET-1758: Ensure currentSchemeStatus for fastpass candidates is set

- app/services/application/ApplicationService.scala
- app/services/assessmentcentre/AssessmentCentreService.scala
- test/services/application/ApplicationServiceSpec.scala
Removed the specific handling of sdip faststream from withdrawal so we first test scenarios without this code and then plug the gaps
> FSET-1780 Removed sdip faststream specific withdrawal handling code

- app/controllers/testdata/TestJobsController.scala
- app/model/ProgressStatuses.scala
- app/model/command/ProgressResponse.scala
- app/model/report/ProgressStatusesReportLabels.scala
- app/repositories/CommonBSONDocuments.scala
- app/repositories/application/FinalOutcomeRepository.scala
- app/repositories/fsb/FsbRepository.scala
- app/services/application/FinalOutcomeService.scala
- conf/testOnlyDoNotUseInAppConf.routes
- it/repositories/application/FsbMongoRepositorySpec.scala
- test/services/application/FinalOutcomeServiceSpec.scala
Sdip faststream who fail fsac but whose sdip is green should be invited to fsb
> FSET-1845 Sdip faststream who fail fsac but whose sdip is green should be invited to fsb

- app/controllers/fixdata/FixDataConsistencyController.scala
- app/model/sift/FixStuckUser.scala
- app/model/sift/FixUserStuckInSiftEntered.scala
- app/repositories/SchemeRepository.scala
- app/repositories/sift/ApplicationSiftRepository.scala
- app/services/sift/ApplicationSiftService.scala
- conf/app.routes
- it/repositories/sift/ApplicationSiftRepositorySpec.scala
added end points to find and fix candidates who are stuck in SIFT_ENTERED who need to be moved to SIFT_READY because they are no longer in the running for form based schemes so need to just be sifted
> FSET-1875 new end points to fix candidates stuck in SIFT_ENTERED

- app/repositories/assessmentcentre/AssessmentCentreRepository.scala
change fsac evaluation to not re-evaluate candidates who are in terminal states (ALL_FSBS_AND_FSACS_FAILED, ASSESSMENT_CENTRE_FAILED, ELIGIBLE_FOR_JOB_OFFER)
> FSET-1883 change fsac evaluation to not re-evaluate candidates who are in terminal states

- app/services/sift/ApplicationSiftService.scala
need to change the current scheme status back to Green for the scheme that was sifted out by mistake (GovernmentEconomicsService) so the candidate is eligible for sifting again
> FSET-1889 Update current scheme status to allow candidates to be sifted again

- app/repositories/application/GeneralApplicationRepository.scala
If a candidate required adjustments for online tests, they should automatically
require adjustments for FSAC and/or FSB
> FSET-1885: Update candidate adjustments criteria for assessment centres

- app/services/reporting/DuplicateDetectionService.scala
> FSET-1868: (Part 2) Dedupe duplicate results before outputting report

- app/controllers/fixdata/FixDataConsistencyController.scala
- app/services/application/ApplicationService.scala
SdipFaststream candidates who are stuck in online tests with Sdip=Green and eventually "fixed" should receive the SIFT_ENTERED email
> FSET-1903: Notify candidate when they are progressed to sift_entered

- app/services/application/ApplicationService.scala
- app/services/sift/ApplicationSiftService.scala
when rolling back fsac candidates take into account any sift results when generating the current scheme status
> FSET-1936 roll back fsac candidates and take into account sift results

- app/controllers/ReportingController.scala
- test/controllers/report/ReportingControllerSpec.scala
Jira for this is coming, it's just not here yet
> NOJIRA: Add user Id to the assessor allocation report

- app/services/sift/SiftAnswersService.scala
- test/model/command/ProgressResponseExamples.scala
- test/services/sift/SiftAnswersServiceSpec.scala
changes to move the candidate to SIFT_READY upon form submission, taking into account any numeric test requirement
> fset-2052 changes to move the candidate to SIFT_READY upon form submission

- app/services/fastpass/FastPassService.scala
- test/services/adjustmentsmanagement/AdjustmentsManagementServiceSpec.scala
- test/services/fastpass/FastPassServiceSpec.scala
when the fast pass is accepted it now performs the same adjustment check as when the adjustments are applied - time based etray adjustment
> FSET-2059 time based etray adjustment check

- calendarEventsConverter/convert.php
- conf/event-schedule.yaml
…y rows, changed location from London to Virtual for PDFS, EDIP and SDIP)
> FSET-2081 2018/19 campaign events - fifth version

- app/services/application/ApplicationService.scala
Extra condition on an existing endpoint to fix SdipFS candidates stuck in phase3
> HOTFIX: SdipFS Candidates must be in PHASE3_TEST_COMPLETED to be fixed.

- app/connectors/EmailClient.scala
Reverts hmrc/fset-faststream#800
> Revert "NOJIRA temporarily stop sending emails"

- app/controllers/fixdata/FixDataConsistencyController.scala
- app/repositories/application/GeneralApplicationRepository.scala
- app/services/application/ApplicationService.scala
- conf/app.routes
> fset-2207 endpoint to find candidates who have phase2_test_expired and are FS red at phase 1 and sdip green

- app/services/allocation/CandidateAllocationService.scala
- app/services/application/ApplicationService.scala
- test/services/application/ApplicationServiceSpec.scala
> FSET-2239: Ensure withdrawn candidates in FSAC are not eligible for reallocation

- app/config/microserviceAppConfig.scala
- app/config/microserviceGlobal.scala
- app/config/microserviceWiring.scala
- project/MicroServiceBuild.scala
- project/plugins.sbt
Reverts hmrc/fset-faststream#864
> Revert "FSET-2212 upgrade play to 2.5.19 and also other libs to fix logback vulnerability"

- app/config/microserviceAppConfig.scala
- app/config/microserviceGlobal.scala
- app/config/microserviceWiring.scala
- project/MicroServiceBuild.scala
- project/plugins.sbt
Reverts hmrc/fset-faststream#865
> Revert "Revert "FSET-2212 upgrade play to 2.5.19 and also other libs to fix logback vulnerability""

- app/controllers/ReportingController.scala
- app/repositories/application/DiversityQuestionsText.scala
- app/repositories/application/PreviousYearCandidatesDetailsRepository.scala
- app/services/testdata/candidate/InProgressQuestionnaireStatusGenerator.scala
- app/services/testdata/faker/DataFaker.scala
Also tidy up diversity question keys
> FSET-2323 reduce number of columns from 17 to 5 in streaming report

- app/repositories/application/GeneralApplicationRepository.scala
- app/services/allocation/CandidateAllocationService.scala
Reverts hmrc/fset-faststream#980
> Revert "FSET-2316 move candidates to ALL_FSBS_AND_FSACS_FAILED if they fail to attend FSAC"

- conf/schemes.yaml
Reverts hmrc/fset-faststream#995
> Revert "FSET-2535: DAT civilServantEligible is set false"

- app/scheduler/NotifyAssessorsOfNewEventsJob.scala
- app/services/assessor/AssessorService.scala
> FSET-2607 rolled back temp change to test assessor emails

- app/controllers/ReportingController.scala
- app/repositories/QuestionnaireRepository.scala
- build.sbt
New index for QuestionnaireRepo
> fset-2788 added more logging to streamed reports.

- app/controllers/EventsController.scala
- app/model/command/Allocation.scala
- app/repositories/AssessorAllocationRepository.scala
- app/services/allocation/AssessorAllocationService.scala
- conf/app.routes
- test/model/command/AllocationSpec.scala
https://jira.tools.tax.service.gov.uk/browse/FSET-3003
> fset-3003: add endpoint to fix asessor allocation

- app/model/command/Allocation.scala
- app/model/exchange/Allocation.scala
- test/model/command/AllocationSpec.scala
https://jira.tools.tax.service.gov.uk/browse/FSET-3003
> fset-3003: add better logs

- app/repositories/AssessorAllocationRepository.scala
> fset-3003: fix issue with view schedule

- app/controllers/CandidateAllocationController.scala
- app/model/command/Allocation.scala
- app/model/exchange/Allocation.scala
- app/repositories/CandidateAllocationRepository.scala
- app/services/allocation/CandidateAllocationService.scala
- conf/app.routes
https://jira.tools.tax.service.gov.uk/browse/FSET-3013
> fset-3013: bug fix for candidate allocation problem

- app/controllers/testdata/CreateCandidateRequestValidator.scala
- app/model/ProgressStatuses.scala
- app/services/testdata/candidate/CandidateStatusGeneratorFactory.scala
https://jira.tools.tax.service.gov.uk/browse/FSET-3015
> fset-3015: TDG fixes to pass candidate acceptance tests

- app/model/exchange/CandidateEligibleForEvent.scala
- app/repositories/application/GeneralApplicationRepository.scala
- test/controllers/CandidateAllocationControllerSpec.scala
- test/services/allocation/CandidateAllocationServiceSpec.scala
Reverts hmrc/fset-faststream#1165
> Revert "FSET-3031 you cannot remove a candidate from a fsac event after scores have been entered"

- app/controllers/ApplicationController.scala
- app/controllers/ReportingController.scala
- app/model/exchange/AssessorSkill.scala
- app/model/exchange/passmarksettings/PassMarkSettings.scala
- app/model/persisted/eventschedules/Event.scala
- app/model/persisted/fileupload/FileUpload.scala
- app/repositories/FrameworkRepository.scala
- app/repositories/fileupload/FileUploadRepository.scala
- app/services/search/SearchForApplicantService.scala
- app/services/testdata/TestDataGeneratorService.scala
- build.sbt
- it/repositories/fileupload/FileUploadRepositorySpec.scala
- it/services/onlinetesting/phase1/Phase1TestEvaluationSpec.scala
- it/services/onlinetesting/phase2/Phase2TestEvaluationSpec.scala
- it/services/onlinetesting/phase3/Phase3TestEvaluationSpec.scala
- project/AppDependencies.scala
- project/build.properties
- project/plugins.sbt
- test/controllers/ApplicationControllerSpec.scala
- test/controllers/report/ReportingControllerSpec.scala
> FSET-2972: upgrade to scala 2.13.8
